### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/vodafone#1]
- [x] Code Review
- [x] Add @Human018 as repo admin
- [x] Add @Human018 to github org
- [ ] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
cc @Human018 when you have a chance :)

**Comment by atymic** [comment]
cc @Human018

**Comment by atymic** [comment]
cc @Human018
Have you had a chance to PR the code?

**Comment by Human018** [comment]
@atymic Sorry mate, I've been caught up with life. PR all done!

**Comment by atymic** [comment]
All good :)
Reviewing now

**Comment by atymic** [comment]
@Human018 

Everything should be good to go :)
Feel free to tag the first release, then i'll merge the website PR :)

**Comment by Human018** [comment]
@atymic tagged and released.

**Comment by atymic** [comment]
Website PR Merged 🎉 
Closing this now.
